config/routes.rb
Restaurants::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  get "about" => "static_pages#about"

  get "carta" => "static_pages#carta"

  root :to => 'static_pages#home'

  resources :plats

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  attr_accessible :descripcio, :nom

  has_many :plats

  def name
  	nom
  end
end

app/models/plat.rb
class Plat < ActiveRecord::Base
  attr_accessible :descripcio, :nom, :foto, :categoria_id, :preu

  belongs_to :categoria

  def name
  	nom
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/plats_controller.rb
class PlatsController < ApplicationController
  def show

  	@plat  = Plat.find(params[:id])
  	
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home


  end

  def carta

  	if params.has_key?(:mode)
      @mode = params[:mode]
    else
      @mode = "thumbs"
    end

  	@categories = Categoria.all
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plats_helper.rb
module PlatsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title><%=  yield(:title) %></title>
     <%= stylesheet_link_tag    "application", :media => "all" %>
     <%= javascript_include_tag "application" %>
     <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <meta property="og:title" content="<%=  yield(:title) %>"/>
    <meta property="og:image" content="<%=  yield(:image) %>"/>
    <meta property="og:site_name" content="<%=  yield(:title) %>"/>
    <meta property="og:description" content="<%=  yield(:description) %>"/>
  
     
    </head>
    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=261712503942401";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

        <header>
        <header class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
              <%= link_to "RESTAURANT TOUCHIES", root_path, id: "logo" %>
              <nav>
                <ul class="nav pull-right">
                    <li><%= link_to "Carta", carta_path %></li>
                    <li><%= link_to "About", about_path %></li>
                    <% if user_signed_in? %>
                      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                    <% else %>
                      <li><%= link_to "Sign in", new_user_session_path, :method => :get %></li>
                    <% end %>
                </ul>
              </nav>
            </div>

            <%= yield :header_seccio %>

          </div>
        </header>
        <div class="container">
            <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
            <% end %>
            <%= yield %>
        </div>
    </body>
</html>

app/views/plats/show.html.erb
<% provide(:title, @plat.nom) %>
<% provide(:image, @plat.foto) %>
<% provide(:description, @plat.descripcio) %>

<h1><%= @plat.nom %></h1>
<p><%= simple_format @plat.descripcio %></p>
<p style="text-align:center;"><%= image_tag(@plat.foto, :alt => @plat.nom) %></p>

<div class="fb-like" data-href="<%= plat_url(@plat) %>" data-send="false" data-layout="button_count" data-width="150" data-show-faces="false"></div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>
<p>
    <a href="http://omrails.com/">One Month Rails</a>
    is a project to teach 
    <a href="http://rubyonrails.org/">Ruby on Rails</a> 
    in one month. This is the sample application.
</p>

app/views/static_pages/carta.html.erb
<% provide(:title, 'Carta') %>

<% content_for :header_seccio do %>
	<div class="container">
		<div class="btn-toolbar">
			<div class="btn-group">
				<%= link_to carta_path(:mode => "list"), :class => "btn", :id => "icon-th-list" do %>
					<i class="icon-th-list"></i>
				<% end %>
			</div>
			<div class="btn-group" data-toggle="buttons-radio">
				<%= link_to carta_path(:mode => "thumbs"), :class => "btn", :id => "icon-th" do %>
					<i class="icon-th"></i>
				<% end %>
				<%= link_to carta_path(:mode => "thumbs-large"), :class => "btn", :id => "icon-th-large" do %>
					<i class="icon-th-large"></i>
				<% end %>
			</div>
			<div class="btn-group" data-toggle="buttons-radio">
				<% @categories.each do |c| %>
					<%= link_to c.nom, carta_path(:mode => @mode, :anchor => c.nom), :class => "btn" %>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

<% if @mode != 'list' %>

	<% @categories.each do |c| %>
		
		<a name="<%= c.nom %>" style="height:80px; display:block;"></a>
		<h3><%= c.nom %></h3>

		<ul class="thumbnails">

		<% c.plats.each_with_index do |p, index| %>

		<% if @mode == 'thumbs' %>
		  <li class="span4 plat">
		<% else %>
		  <li class="span6 plat">
		<%	end	%>
		    <div class="thumbnail">
		      <%= image_tag(p.foto, :alt => p.nom, :class=>"img-rounded") %>
		      <div class="caption">
		        <h3 style="height:80px; font-size:1.5rem;"><%= p.nom %></h3>
		        <p><%= simple_format truncate(p.descripcio, :length => 100, :separator => " ") %></p>
		        <p><%= link_to "Veure el plat", p, class: "btn btn-success" %>
		        	<button class="btn"><%= number_with_precision(p.preu, :precision => 2) %> €</button>
		        	<div class="fb-like" data-href="<%= plat_url(p) %>" data-send="false" data-layout="button_count" data-width="150" data-show-faces="false"></div>
		       	</p>
		      </div>
		    </div>
		  </li>
		  
		  <%	end	%>

		</ul>

	<%	end	%>

<% else %>

	<% @categories.each do |c| %>

		<a name="<%= c.nom %>" style="height:80px; display:block;"></a>
		<h3><%= c.nom %></h3>

		<div class="accordion" id="accordion<%= c.id %>">

		<% c.plats.each_with_index do |p, index| %>
		
		  <div class="accordion-group">
		    <div class="accordion-heading">
		      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion<%= c.id %>" data-target="#collapse<%= p.id %>">
		        <%= p.nom %>
		      </a>
		    </div>
		    <div id="collapse<%= p.id %>" class="accordion-body collapse">
		      <div class="accordion-inner media">
		      	<div class="pull-left"><%= image_tag(p.foto, :alt => p.nom, :size=>"100x100", :class=>"img-rounded media-object") %></div>
		      	<div class="media-body">
			        <%= simple_format p.descripcio %><br /><br />
			        <%= link_to "Veure el plat", p, class: "btn btn-success" %><button class="btn"><%= number_with_precision(p.preu, :precision => 2) %> €</button>
			        <div class="fb-like" data-href="<%= plat_url(p) %>" data-send="false" data-layout="button_count" data-width="150" data-show-faces="false"></div>
			    </div>
		      </div>
		    </div>
		  </div>
		
		<%	end	%>

		</div>

	<%	end	%>

<%	end	%>

app/views/static_pages/home.html.erb
<% provide(:title, 'Restaurant Touchies') %>

<% if user_signed_in? %>

	
	<div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
          <div class="item active">
            <%= image_tag("Divinic01p.jpg") %>
            <div class="carousel-caption">
              <h4>Third Thumbnail label</h4>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
          </div>
          <div class="item">
            <%= image_tag("Divinic02p.jpg") %>
            <div class="carousel-caption">
              <h4>Third Thumbnail label</h4>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
          </div>
          <div class="item">
            <%= image_tag("Divinic03p.jpg") %>
            <div class="carousel-caption">
              <h4>Third Thumbnail label</h4>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
          </div>
          <div class="item">
            <%= image_tag("Divinic04p.jpg") %>
            <div class="carousel-caption">
              <h4>Third Thumbnail label</h4>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
          </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
      </div>
  </div>

  <div class="container">
	  <div class="row">
	    <div class="span4">
	    	<%= image_tag("http://distilleryimage6.s3.amazonaws.com/2864ccbc319811e2b8e822000a1fbcc7_7.jpg", :width => '60%', :style => "margin-left:20%", :class => "img-rounded") %>
	      <h2>Heading</h2>
	      <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
	      <p><a class="btn" href="#">View details &raquo;</a></p>
	    </div><!-- /.span4 -->
	    <div class="span4">
	      <%= image_tag("pressec.jpg", :width => '60%', :style => "margin-left:20%", :class => "img-rounded") %>
	      <h2>Heading</h2>
	      <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
	      <p><a class="btn" href="#">View details &raquo;</a></p>
	    </div><!-- /.span4 -->
	    <div class="span4">
	      <%= image_tag("enoturisme.jpg", :width => '60%', :style => "margin-left:20%", :class => "img-rounded") %>
	      <h2>Heading</h2>
	      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
	      <p><a class="btn" href="#">View details &raquo;</a></p>
	    </div><!-- /.span4 -->
	  </div>
</div>
	

<% else %>
	<div class="center hero-unit">
	    <h1>Restaurant Touchies</h1>

	    <h2>
	      <!--Gestiona el dia a dia del teu restaurant sense complicar-te la vida.-->
	      Benvinguts a la nostra pàgina. Per poder accedir t'has de donar d'alta com a usuari.
	    </h2>

	    <%= link_to "Donar-se d'alta", new_user_registration_path, class: "btn btn-large btn-primary" %>
	</div>
<% end %>